### ISSUE TITLE
Поправить ошибку при добавлении нового дерева

### ISSUE THREAD

**Issue by netForceoff** [Yekaterinburg-Tree-Map/ekbtrees-backend#35]
There is no getter for property named 'numberTreeTrunks' in 'class ru.naumen.ectmapi.entity.Tree'
 at org.apache.ibatis.reflection.Reflector.getGetInvoker(Reflector.java:374) ~[mybatis-3.5.6.jar:3.5.6]
 at org.apache.ibatis.reflection.MetaClass.getGetInvoker(MetaClass.java:164) ~[mybatis-3.5.6.jar:3.5.6]
 at org.apache.ibatis.reflection.wrapper.BeanWrapper.getBeanProperty(BeanWrapper.java:162) ~[mybatis-3.5.6.jar:3.5.6]
 at org.apache.ibatis.reflection.wrapper.BeanWrapper.get(BeanWrapper.java:49) ~[mybatis-3.5.6.jar:3.5.6]
 at org.apache.ibatis.reflection.MetaObject.getValue(MetaObject.java:122) ~[mybatis-3.5.6.jar:3.5.6]

**Comment by yulia-matveeva** [comment]
Не актуально, нужно закрыть задачу
